services:
  proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - ./data/npm:/data
      - ./data/letsencrypt:/etc/letsencrypt
  frontend:
    build: ./frontend
    environment:
      - API_URL=http://api.meicm.pt
  api:
    build: ./api
    depends_on:
      - cache-db
    environment:
      - REDIS_URL=redis://cache-db:6379
  cache-db:
    image: redis